    
name: WVU Brand Patterns
description: This is the WVU Brand Patterns theme built for CleanSlate. Originally authored by Adam Glenn.

# CSS
css: 
  
  # Turn CSS compression/minification on/off.
  compress: true
  
# JavaScript options
js:
  
  # Turn JavaScript compression/minification on/off
  compress: true
  
  # Turn JavaScript mangling on/off.
  mangle: true